-- ==========================================================================
-- English Grammar for Fellows — Units 9–11 Seed Data (LESSONS ONLY)
-- Generated by scripts/export-seed-sql-unit9-11.ts
-- Uses $$ dollar-quoting for JSONB to preserve apostrophes, quotes, arrows.
-- Safe to run multiple times (idempotent via ON CONFLICT DO UPDATE).
-- Does NOT delete users, exercise_attempts, or lesson_progress.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- Unit 9: May / Might (5 lessons)
-- --------------------------------------------------------------------------

INSERT INTO units (id, unit_number, title, lesson_count, exercise_count, question_count)
VALUES ('00000009-0000-4000-8000-000000000001', 9, 'May / Might', 5, 1, 16)
ON CONFLICT (unit_number) DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  lesson_count = EXCLUDED.lesson_count,
  exercise_count = EXCLUDED.exercise_count,
  question_count = EXCLUDED.question_count;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00009000-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 9),
  'unit9-lesson1',
  'May for Possibility',
  $$'May' is used to express possibility. It suggests something is possible but not certain. The structure is Subject + may + V1.$$,
  $${"details":[{"concept":"Possibility","explanation":"'May' is used when something is possible but not certain.","example":"He may be at home.","burmese":"သူ အိမ်မှာ ရှိနိုင်တယ်။"},{"concept":"Possibility (Weather)","explanation":"'May' is used for possible future events like weather.","example":"It may rain tomorrow.","burmese":"မနက်ဖန် မိုးရွာနိုင်တယ်။"}]}$$::jsonb,
  1
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00009001-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 9),
  'unit9-lesson2',
  'May for Permission',
  $$'May' is used to express permission. 'May not' is used to deny permission. This is a formal way to ask for or give permission.$$,
  $${"details":[{"concept":"Asking Permission","explanation":"'May' is used to politely ask for permission.","example":"May I come in, Sir? Yes, you may.","burmese":"ဆရာ၊ ဝင်လို့ ရမလား။ ရတယ်၊ ဝင်လို့ရတယ်။"},{"concept":"Denying Permission","explanation":"'May not' is used to deny permission.","example":"May I go home now? No, you may not.","burmese":"အခု အိမ်ပြန်လို့ ရမလား။ မရဘူး၊ ပြန်လို့ မရဘူး။"}]}$$::jsonb,
  2
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00009002-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 9),
  'unit9-lesson3',
  'May for Wishes',
  $$'May' is used to express wishes or hopes. This is often used in formal or literary expressions.$$,
  $${"details":[{"concept":"Blessing","explanation":"'May' is used to express blessings and good wishes.","example":"May God bless you!","burmese":"ဘုရားသခင် ကောင်းကြီးပေးပါစေ!"},{"concept":"Peace Wish","explanation":"'May' is used to wish peace for someone.","example":"May his soul rest in peace!","burmese":"သူ့ဝိညာဉ် ငြိမ်းချမ်းစွာ ရောက်ရှိပါစေ!"},{"concept":"Contribution Wish","explanation":"'May' is used to wish success in contributing.","example":"May you contribute the community!","burmese":"လူမှုအသိုင်းအဝိုင်းအတွက် ပါဝင်ကူညီနိုင်ပါစေ!"}]}$$::jsonb,
  3
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00009003-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 9),
  'unit9-lesson4',
  'Might as Past Tense of May (Reported Speech)',
  $$'Might' is the past tense of 'may' in indirect or reported speech. When we report what someone said, 'may' changes to 'might'.$$,
  $${"details":[{"concept":"Reported Speech","explanation":"In reported speech, 'may' changes to 'might'.","example":"He said, \"I may go to school.\" → He said that he might go to school.","burmese":"သူက \"ငါကျောင်းသွားနိုင်တယ်\" လို့ပြောခဲ့တယ်။ → သူက ကျောင်းသွားနိုင်တယ်လို့ ပြောခဲ့တယ်။"},{"concept":"Reported Speech (Writing)","explanation":"The same rule applies for writing activities.","example":"John said, \"I may write a letter.\" → John said that he might write a letter.","burmese":"ဂျွန်က \"ငါစာရေးနိုင်တယ်\" လို့ပြောခဲ့တယ်။ → ဂျွန်က စာရေးနိုင်တယ်လို့ ပြောခဲ့တယ်။"}]}$$::jsonb,
  4
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00009004-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 9),
  'unit9-lesson5',
  'Might for Less Possibility',
  $$'Might' shows less possibility than 'may'. May suggests about 50% possibility, while might suggests about 30% possibility.$$,
  $${"details":[{"concept":"Higher Possibility (May)","explanation":"'May' suggests a higher chance of something happening (about 50%).","example":"It may rain. (Maybe a 50% possibility)","burmese":"မိုးရွာနိုင်တယ်။ (ဖြစ်နိုင်ခြေ ရာခိုင်နှုန်း ၅၀ ရှိတယ်)"},{"concept":"Lower Possibility (Might)","explanation":"'Might' suggests a lower chance of something happening (about 30%).","example":"It might rain. (Maybe a 30% possibility)","burmese":"မိုးရွာနိုင်တယ်။ (ဖြစ်နိုင်ခြေ ရာခိုင်နှုန်း ၃၀ ရှိတယ်)"}]}$$::jsonb,
  5
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

-- --------------------------------------------------------------------------
-- Unit 10: Must (4 lessons)
-- --------------------------------------------------------------------------

INSERT INTO units (id, unit_number, title, lesson_count, exercise_count, question_count)
VALUES ('00000010-0000-4000-8000-000000000001', 10, 'Must', 4, 1, 15)
ON CONFLICT (unit_number) DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  lesson_count = EXCLUDED.lesson_count,
  exercise_count = EXCLUDED.exercise_count,
  question_count = EXCLUDED.question_count;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00010000-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 10),
  'unit10-lesson1',
  'Must for Strong Obligation',
  $$'Must' is used for strong personal obligations. It expresses something that is necessary or very important. The structure is Subject + must + V1.$$,
  $${"details":[{"concept":"Personal Obligation","explanation":"'Must' is used for obligations that come from yourself or are very important.","example":"I must lose some weight.","burmese":"ငါ ဝိတ်ချရမယ်။"},{"concept":"Duty Obligation","explanation":"'Must' is used for duties and responsibilities.","example":"I must write a letter to John.","burmese":"ငါ ဂျွန်ဆီ စာတစ်စောင် ရေးရမယ်။"},{"concept":"Important Rule","explanation":"'Must' is used for important rules that must be followed.","example":"Bicyclists must remember to signal when they turn.","burmese":"စက်ဘီးစီးသူများ လှည့်တဲ့အခါ အမှတ်ပေးဖို့ မှတ်ထားရမယ်။"},{"concept":"Exam Obligation","explanation":"'Must' is used for obligations related to exams and studies.","example":"He must study harder if he wants to pass the exam.","burmese":"သူ စာမေးပွဲ အောင်ချင်ရင် ပိုပြီး ကြိုးစားရမယ်။"}]}$$::jsonb,
  1
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00010001-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 10),
  'unit10-lesson2',
  'Mustn''t for Prohibition',
  $$'Mustn't' (must not) is used to express that something is prohibited or not allowed. The structure is Subject + mustn't + V1.$$,
  $${"details":[{"concept":"Transport Prohibition","explanation":"'Mustn't' is used for rules about transport safety.","example":"Passengers mustn't talk to the driver.","burmese":"ခရီးသည်များ ဒီရင်ဘောက် စကားမပြောခင်းမရပါ။"},{"concept":"Workplace Prohibition","explanation":"'Mustn't' is used for workplace rules.","example":"Policemen mustn't drink on duty.","burmese":"ရဲတပ်ဖွဲ့ဝင်များ တာဝန်ထမ်းဆောင်နေချိန်မှာ အရက်မသောက်ရပါ။"},{"concept":"Children Prohibition","explanation":"'Mustn't' is used for rules about children.","example":"Children mustn't eat chewing gum.","burmese":"ကလေးများ ဝါဂွမ်းမစားရပါ။"},{"concept":"Classroom Prohibition","explanation":"'Mustn't' is used for classroom rules.","example":"They mustn't use their mobile phones during lessons.","burmese":"သူတို့ သင်ခန်းစာချိန်မှာ မိုဘိုင်းဖုန်းများ အသုံးမပြုရပါ။"}]}$$::jsonb,
  2
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00010002-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 10),
  'unit10-lesson3',
  'Must in Questions',
  $$'Must' can be used in questions to ask about obligation. The structure is Must + subject + V1?$$,
  $${"details":[{"concept":"Asking About Obligation","explanation":"'Must' is used to ask if something is required.","example":"Must I go to the party?","burmese":"ကျွန်တော် ပါတီသွားရမလား။"},{"concept":"Asking About Necessity","explanation":"'Must' is used to ask about the necessity of an action.","example":"Must he make so much noise?","burmese":"သူ ဆူညံစွာ လုပ်ရမလား။"}]}$$::jsonb,
  3
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00010003-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 10),
  'unit10-lesson4',
  'Important Notes About Must',
  $$'Must' is used only in the present and future. The past form of 'must' is 'had to'. 'Must' does not exist in the past tense.$$,
  $${"details":[{"concept":"Present and Future Only","explanation":"'Must' can only be used for present and future obligations.","example":"I must finish this work before I leave.","burmese":"ငါ ထွက်ခင် ဒီအလုပ်ကို ပြီးအောင်လုပ်ရမယ်။"},{"concept":"Past Form is Had To","explanation":"For past obligations, use 'had to' instead of 'must'.","example":"I had to finish the work yesterday. (Not: I musted finish)","burmese":"ငါ မနေ့က ဒီအလုပ်ကို ပြီးအောင်လုပ်ရတယ်။"}]}$$::jsonb,
  4
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

-- --------------------------------------------------------------------------
-- Unit 11: Have to (3 lessons)
-- --------------------------------------------------------------------------

INSERT INTO units (id, unit_number, title, lesson_count, exercise_count, question_count)
VALUES ('00000011-0000-4000-8000-000000000001', 11, 'Have to', 3, 1, 15)
ON CONFLICT (unit_number) DO UPDATE SET
  id = EXCLUDED.id,
  title = EXCLUDED.title,
  lesson_count = EXCLUDED.lesson_count,
  exercise_count = EXCLUDED.exercise_count,
  question_count = EXCLUDED.question_count;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00011000-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 11),
  'unit11-lesson1',
  'Have to for Responsibilities',
  $$'Have to' is used for responsibilities at work and in everyday life. It is conjugated as a regular verb and requires an auxiliary verb in questions and negatives. The structure is Subject + have to + V1.$$,
  $${"details":[{"concept":"Work Responsibility","explanation":"'Have to' is used for work-related responsibilities.","example":"I have to write a letter to John.","burmese":"ကျွန်တော် ဂျွန်ဆီ စာတစ်စောင် ရေးစရာရှိတယ်။"},{"concept":"Schedule Conflict","explanation":"'Have to' is used when something prevents you from doing something else.","example":"Mike can't come because he has to work tomorrow.","burmese":"မိုက် အလပ်လပ်စရာရှိလို့ သူ မလာနိုင်ဘူး။"},{"concept":"Education Responsibility","explanation":"'Have to' is used for educational requirements.","example":"Children have to go to school.","burmese":"ကလေးများ ကျောင်းသွားရမယ်။"},{"concept":"Health Responsibility","explanation":"'Have to' is used for health-related obligations.","example":"He has to see the doctor.","burmese":"သူ ဆရာဝန်ဆီ သွားရမယ်။"}]}$$::jsonb,
  1
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00011001-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 11),
  'unit11-lesson2',
  'Don''t Have to for Not Required',
  $$'Don't have to' is used to express that something is not required or not necessary. The structure is Subject + don't/doesn't have to + V1.$$,
  $${"details":[{"concept":"Not Required (Sunday)","explanation":"'Don't have to' means something is not necessary.","example":"I don't have to work on Sundays so I can do what I want.","burmese":"ကျွန်တော် တနင်္ဂနွေနေ့တွေ အလပ်မရဘူး။ ဒါကြောင့် ငါ ဘာလုပ်ချင်တာလုပ်နိုင်တယ်။"},{"concept":"Not Required (Meeting)","explanation":"'Don't have to' means attendance is optional.","example":"She doesn't have to come to the meeting if she doesn't want to.","burmese":"အစည်းအဝေး မလာချင်ရင် မလာပါနဲ့။"},{"concept":"Not Required (Driving)","explanation":"'Don't have to' means driving is not necessary.","example":"You don't have to drive today.","burmese":"မင်း ဒီနေ့ မောင်းစရာ မလိုဘူး။"},{"concept":"Not Required (Language)","explanation":"'Don't have to' means learning a language is not necessary.","example":"She doesn't have to learn your language.","burmese":"သူမ မင်းဘာသာစကား သင်စရာ မလိုဘူး။"}]}$$::jsonb,
  2
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

INSERT INTO lessons (id, unit_id, slug, title, content, data, sort_order)
VALUES (
  '00011002-0000-4000-8000-000000000002',
  (SELECT id FROM units WHERE unit_number = 11),
  'unit11-lesson3',
  'Have to in Past, Present, and Future',
  $$'Have to' is used in all three tenses. The past form is 'had to'. Questions in the past use 'Did + subject + have to'.$$,
  $${"details":[{"concept":"Present Tense","explanation":"Use 'have to' or 'has to' for present obligations.","example":"I have to file reports every week.","burmese":"ငါ အပတ်တိုင်း အစီရင်ခံစာ တင်ရမယ်။"},{"concept":"Past Tense","explanation":"Use 'had to' for past obligations.","example":"She had to pick the children up from school yesterday.","burmese":"သူမ မနေ့က ကလေးတွေကို ကျောင်းကနေ ခေါ်လာခရတယ်။"},{"concept":"Past Question","explanation":"Use 'Did + subject + have to' for past questions.","example":"Did he have to leave so early?","burmese":"သူ အစောစောထွက်လိုက်ရတာလား။"},{"concept":"Past Tense (Dentist)","explanation":"'Had to' is used for past obligations like doctor visits.","example":"I had to go to the dentist yesterday.","burmese":"ငါ မနေ့က သွားဆရာဝန်ဆီ သွားရတယ်။"},{"concept":"Past Question (Work)","explanation":"'Did + have to' is used to ask about past work obligations.","example":"Did they have to do the work over again?","burmese":"သူတို့ အလုပ်ကို ပြန်လုပ်ရတာလား။"}]}$$::jsonb,
  3
)
ON CONFLICT (unit_id, slug) DO UPDATE SET title = EXCLUDED.title, content = EXCLUDED.content, data = EXCLUDED.data, sort_order = EXCLUDED.sort_order;

-- ==========================================================================
-- END OF LESSON SEED DATA
-- ==========================================================================
